### PR TITLE
fix: Propagate bp-managed errors and show full validation output

### LINKED ISSUE #69: [bug] template validation swallows `bp-managed` lookup errors, causing unrelated validation errors
**Describe the bug**
I was missing a `bp-managed` dependency and `cargo test` was generating an un-rendered `Cargo.toml` and then giving an error about not having a dependency source for a different error.

**To Reproduce**

1. Go to the cli simple template
2. Add an unknown `bp-managed` dependency
3. Run `cargo test

** If related, what battery pack were you using?**: cli

**Expected behavior**
A direct error about the failure

**Screenshots**

**Metadata**

1. What is the version of `battery-pack`? latest master
2. What operating system are you using? Linux

- [x] I have tried to reproduce this on a clean, new project and it still happens.

**Additional context**

See
https://github.com/battery-pack-rs/battery-pack/blob/7d254d7565de7302f2f32a85b9c3fa7760c8aea9/src/battery-pack/bphelper-cli/src/template_engine.rs#L197-L200

### PR DESCRIPTION
**Pull request by jlizen**
Fixes: #69, #73 

69 - we were just not logging the error, we now do.

73 - we were missing stdout, only showing stderr, but stdout had the interesting info

There are regression tests for each.

### CODE REVIEW

File: src/battery-pack/bphelper-cli/src/template_engine/tests.rs [hunk 1]
```diff
@@ -308,3 +308,64 @@ fn preview_resolves_bp_managed_deps() {
...
+
+#[test]
+fn preview_warns_on_unresolvable_bp_managed_dep() {
+    let tmp = tempfile::tempdir().unwrap();
+    let crate_root = tmp.path();
+
+    // Minimal battery pack Cargo.toml
+    std::fs::write(
+        crate_root.join("Cargo.toml"),
+        r#"[package]
```
Comment (nikomatsakis) [inline src/battery-pack/bphelper-cli/src/template_engine/tests.rs]: nit: let's use `indoc` crate for these multiline string literals

File: src/battery-pack/bphelper-cli/src/template_engine/tests.rs [hunk 2]
```diff
@@ -308,3 +308,64 @@ fn preview_resolves_bp_managed_deps() {
...
+    };
+
+    // Should succeed (warn, not error) since the battery pack may not exist yet
+    let files = preview(opts).unwrap();
+    let cargo = files.iter().find(|f| f.path == "Cargo.toml").unwrap();
+    // The bp-managed marker should still be present (unresolved)
+    assert!(
+        cargo.content.contains("bp-managed"),
+        "unresolved bp-managed dep should remain in output"
+    );
```
Comment (nikomatsakis) [inline src/battery-pack/bphelper-cli/src/template_engine/tests.rs:395]: nit: I would add `expect_test` here in addition to the `assert` so we can see the full output.

File: src/battery-pack/bphelper-cli/src/validate/tests.rs [hunk 3]
```diff
@@ -122,3 +122,58 @@ fn validate_fixture_with_repository_no_warning() {
...
+    )
+    .unwrap();
+
+    let err = super::validate_templates(bp.to_str().unwrap()).unwrap_err();
+    let msg = format!("{err:#}");
+
+    assert!(
+        msg.contains("THIS DETAIL SHOULD BE VISIBLE"),
+        "error should include stdout with test failure details, got:\n{msg}"
+    );
```
Comment (nikomatsakis) [inline src/battery-pack/bphelper-cli/src/validate/tests.rs:211]: expect-test

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/battery-pack/bphelper-cli/src/validate/tests.rs (hunk 3 above)
Comment (jlizen) [reply src/battery-pack/bphelper-cli/src/validate/tests.rs:211]: snapbox now, thanks. let me add a testing section to steering.

Comment (jlizen) [reply src/battery-pack/bphelper-cli/src/validate/tests.rs:211]: Related: #95

File: src/battery-pack/bphelper-cli/src/commands/tests.rs [hunk 4]
```diff
@@ -1379,7 +1362,7 @@ fn add_target_package_writes_metadata() {
 }
 
 // ============================================================================
-// build.rs creation
+// build.rs is no longer created (validate() was removed)
 // ============================================================================
```
Comment (nikomatsakis) [inline src/battery-pack/bphelper-cli/src/commands/tests.rs:1366]:
```suggestion
```

File: src/battery-pack/bphelper-cli/src/commands/tests.rs [hunk 5]
```diff
@@ -1379,7 +1362,7 @@ fn add_target_package_writes_metadata() {
 }
 
 // ============================================================================
```
Comment (nikomatsakis) [inline src/battery-pack/bphelper-cli/src/commands/tests.rs:1364]:
```suggestion
```

File: src/battery-pack/bphelper-cli/src/commands/tests.rs (hunk 4 above)
Comment (nikomatsakis) [inline src/battery-pack/bphelper-cli/src/commands/tests.rs:1366]:
```suggestion
```

File: src/battery-pack/bphelper-cli/src/commands/tests.rs [hunk 6]
```diff
@@ -1396,9 +1379,10 @@ fn add_creates_build_rs() {
         tmp.path(),
     );
 
-    let build_rs = std::fs::read_to_string(tmp.path().join("build.rs")).unwrap();
-
-    assert_data_eq!(build_rs, file![_]);
+    assert!(
+        !tmp.path().join("build.rs").exists(),
+        "build.rs should not be created (validate() was removed)"
```
Comment (nikomatsakis) [inline src/battery-pack/bphelper-cli/src/commands/tests.rs:1384]:
```suggestion
        "build.rs should not be created"
```

**Review by nikomatsakis — APPROVED** [review]
meh, let's just merge it, comments are a bit "journey not destination" but whatever

**Comment by jlizen** [comment]
Oh I would've committed them ^^

**Comment by jlizen** [comment]
If you are at a comp, glad to stamp a follow up with them @nikomatsakis
